-- MySQL Script generated by MySQL Workbench
-- mié 09 ene 2019 18:53:51 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema casafacil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema casafacil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casafacil` DEFAULT CHARACTER SET utf8 ;
USE `casafacil` ;

-- -----------------------------------------------------
-- Table `casafacil`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`tipousuario` (
  `id_tipousuario` INT NOT NULL,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id_tipousuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nickname` VARCHAR(255) NULL,
  `nombre` VARCHAR(255) NULL,
  `apellido1` VARCHAR(255) NULL,
  `apellido2` VARCHAR(255) NULL,
  `correo` VARCHAR(255) NULL,
  `telefono` INT NULL,
  `password` VARCHAR(255) NULL,
  `id_tipousuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_tipousuario1_idx` (`id_tipousuario` ASC),
  CONSTRAINT `fk_usuario_tipousuario1`
    FOREIGN KEY (`id_tipousuario`)
    REFERENCES `casafacil`.`tipousuario` (`id_tipousuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`tipoinmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`tipoinmueble` (
  `id_tipoinmueble` INT NOT NULL,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id_tipoinmueble`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`tipovia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`tipovia` (
  `id_tipovia` INT NOT NULL,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id_tipovia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`ciudad` (
  `id_ciudad` INT NOT NULL,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id_ciudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`barrio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`barrio` (
  `id_barrio` INT NOT NULL,
  `desc` VARCHAR(255) NULL,
  `codpostal` INT NULL,
  `id_ciudad` INT NOT NULL,
  PRIMARY KEY (`id_barrio`),
  INDEX `fk_barrio_ciudad1_idx` (`id_ciudad` ASC),
  CONSTRAINT `fk_barrio_ciudad1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `casafacil`.`ciudad` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`anuncio` (
  `id_anuncio` INT NOT NULL,
  `titulo` VARCHAR(255) NULL,
  `habitaciones` INT NULL,
  `baños` INT NULL,
  `metroscasa` INT NULL,
  `metrosterreno` INT NULL,
  `direccion` VARCHAR(255) NULL,
  `fechacreacion` DATE NULL,
  `fechaupdate` DATE NULL,
  `precio` INT NULL,
  `descripcion` MEDIUMTEXT NULL,
  `id_usuario` INT NOT NULL,
  `id_tipoinmueble` INT NOT NULL,
  `id_tipovia` INT NOT NULL,
  `id_barrio` INT NOT NULL,
  PRIMARY KEY (`id_anuncio`),
  INDEX `fk_anuncio_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_anuncio_tipoinmueble1_idx` (`id_tipoinmueble` ASC),
  INDEX `fk_anuncio_tipovia1_idx` (`id_tipovia` ASC),
  INDEX `fk_anuncio_barrio1_idx` (`id_barrio` ASC),
  CONSTRAINT `fk_anuncio_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `casafacil`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_tipoinmueble1`
    FOREIGN KEY (`id_tipoinmueble`)
    REFERENCES `casafacil`.`tipoinmueble` (`id_tipoinmueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_tipovia1`
    FOREIGN KEY (`id_tipovia`)
    REFERENCES `casafacil`.`tipovia` (`id_tipovia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_barrio1`
    FOREIGN KEY (`id_barrio`)
    REFERENCES `casafacil`.`barrio` (`id_barrio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`extras` (
  `id_extras` INT NOT NULL,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id_extras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`extras_anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`extras_anuncio` (
  `id_anuncio` INT NOT NULL,
  `id_extras` INT NOT NULL,
  PRIMARY KEY (`id_anuncio`, `id_extras`),
  INDEX `fk_Anuncio_has_Extras_Extras1_idx` (`id_extras` ASC),
  INDEX `fk_Anuncio_has_Extras_Anuncio_idx` (`id_anuncio` ASC),
  CONSTRAINT `fk_Anuncio_has_Extras_Anuncio`
    FOREIGN KEY (`id_anuncio`)
    REFERENCES `casafacil`.`anuncio` (`id_anuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anuncio_has_Extras_Extras1`
    FOREIGN KEY (`id_extras`)
    REFERENCES `casafacil`.`extras` (`id_extras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`favoritos` (
  `id_usuario` INT NOT NULL,
  `id_anuncio` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_anuncio`),
  INDEX `fk_usuario_has_anuncio_anuncio1_idx` (`id_anuncio` ASC),
  INDEX `fk_usuario_has_anuncio_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_usuario_has_anuncio_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `casafacil`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_anuncio_anuncio1`
    FOREIGN KEY (`id_anuncio`)
    REFERENCES `casafacil`.`anuncio` (`id_anuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`fotos` (
  `id_fotos` INT NOT NULL,
  `ruta` VARCHAR(255) NULL,
  PRIMARY KEY (`id_fotos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`fotos_anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`fotos_anuncio` (
  `id_anuncio` INT NOT NULL,
  `id_fotos` INT NOT NULL,
  PRIMARY KEY (`id_anuncio`, `id_fotos`),
  INDEX `fk_anuncio_has_fotos_fotos1_idx` (`id_fotos` ASC),
  INDEX `fk_anuncio_has_fotos_anuncio1_idx` (`id_anuncio` ASC),
  CONSTRAINT `fk_anuncio_has_fotos_anuncio1`
    FOREIGN KEY (`id_anuncio`)
    REFERENCES `casafacil`.`anuncio` (`id_anuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_has_fotos_fotos1`
    FOREIGN KEY (`id_fotos`)
    REFERENCES `casafacil`.`fotos` (`id_fotos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
