-- MySQL Script generated by MySQL Workbench
-- lun 14 ene 2019 23:04:58 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema casafacil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema casafacil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casafacil` DEFAULT CHARACTER SET utf8 ;
USE `casafacil` ;

-- -----------------------------------------------------
-- Table `casafacil`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`tipousuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(255) NULL,
  `nombre` VARCHAR(255) NULL,
  `apellido1` VARCHAR(255) NULL,
  `apellido2` VARCHAR(255) NULL,
  `correo` VARCHAR(255) NULL,
  `telefono` INT NULL,
  `password` VARCHAR(255) NULL,
  `id_tipousuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipousuario1_idx` (`id_tipousuario` ASC),
  CONSTRAINT `fk_usuario_tipousuario1`
    FOREIGN KEY (`id_tipousuario`)
    REFERENCES `casafacil`.`tipousuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`tipoinmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`tipoinmueble` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`tipovia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`tipovia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`barrio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`barrio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NULL,
  `codpostal` INT NULL,
  `id_ciudad` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_barrio_ciudad1_idx` (`id_ciudad` ASC),
  CONSTRAINT `fk_barrio_ciudad1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `casafacil`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`anuncio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL,
  `habitaciones` INT NULL,
  `banyos` INT NULL,
  `metroscasa` INT NULL,
  `metrosterreno` INT NULL,
  `direccion` VARCHAR(255) NULL,
  `fechacreacion` DATETIME NULL,
  `fechaupdate` DATETIME NULL,
  `precio` INT NULL,
  `descripcion` MEDIUMTEXT NULL,
  `id_usuario` INT NOT NULL,
  `id_tipoinmueble` INT NOT NULL,
  `id_tipovia` INT NOT NULL,
  `id_barrio` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_anuncio_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_anuncio_tipoinmueble1_idx` (`id_tipoinmueble` ASC),
  INDEX `fk_anuncio_tipovia1_idx` (`id_tipovia` ASC),
  INDEX `fk_anuncio_barrio1_idx` (`id_barrio` ASC),
  CONSTRAINT `fk_anuncio_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `casafacil`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_tipoinmueble1`
    FOREIGN KEY (`id_tipoinmueble`)
    REFERENCES `casafacil`.`tipoinmueble` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_tipovia1`
    FOREIGN KEY (`id_tipovia`)
    REFERENCES `casafacil`.`tipovia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_barrio1`
    FOREIGN KEY (`id_barrio`)
    REFERENCES `casafacil`.`barrio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`extras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`extras_anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`extras_anuncio` (
  `id_anuncio` INT NOT NULL,
  `id_extras` INT NOT NULL,
  PRIMARY KEY (`id_anuncio`, `id_extras`),
  INDEX `fk_Anuncio_has_Extras_Extras1_idx` (`id_extras` ASC),
  INDEX `fk_Anuncio_has_Extras_Anuncio_idx` (`id_anuncio` ASC),
  CONSTRAINT `fk_Anuncio_has_Extras_Anuncio`
    FOREIGN KEY (`id_anuncio`)
    REFERENCES `casafacil`.`anuncio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anuncio_has_Extras_Extras1`
    FOREIGN KEY (`id_extras`)
    REFERENCES `casafacil`.`extras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`favoritos` (
  `id_usuario` INT NOT NULL,
  `id_anuncio` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_anuncio`),
  INDEX `fk_usuario_has_anuncio_anuncio1_idx` (`id_anuncio` ASC),
  INDEX `fk_usuario_has_anuncio_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_usuario_has_anuncio_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `casafacil`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_anuncio_anuncio1`
    FOREIGN KEY (`id_anuncio`)
    REFERENCES `casafacil`.`anuncio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casafacil`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casafacil`.`fotos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(255) NULL,
  `id_anuncio` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fotos_anuncio1_idx` (`id_anuncio` ASC),
  CONSTRAINT `fk_fotos_anuncio1`
    FOREIGN KEY (`id_anuncio`)
    REFERENCES `casafacil`.`anuncio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `casafacil`.`tipousuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `casafacil`;
INSERT INTO `casafacil`.`tipousuario` (`id`, `desc`) VALUES (1, 'Administrador');
INSERT INTO `casafacil`.`tipousuario` (`id`, `desc`) VALUES (2, 'Cliente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `casafacil`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `casafacil`;
INSERT INTO `casafacil`.`usuario` (`id`, `nickname`, `nombre`, `apellido1`, `apellido2`, `correo`, `telefono`, `password`, `id_tipousuario`) VALUES (1, 'admin', 'nombre', 'ape1', 'ape2', 'correo@correo.es', 657465213, 'admin', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `casafacil`.`tipoinmueble`
-- -----------------------------------------------------
START TRANSACTION;
USE `casafacil`;
INSERT INTO `casafacil`.`tipoinmueble` (`id`, `desc`) VALUES (1, 'Piso');
INSERT INTO `casafacil`.`tipoinmueble` (`id`, `desc`) VALUES (2, 'Casa');
INSERT INTO `casafacil`.`tipoinmueble` (`id`, `desc`) VALUES (3, 'Chalet');
INSERT INTO `casafacil`.`tipoinmueble` (`id`, `desc`) VALUES (4, 'Ático');

COMMIT;


-- -----------------------------------------------------
-- Data for table `casafacil`.`tipovia`
-- -----------------------------------------------------
START TRANSACTION;
USE `casafacil`;
INSERT INTO `casafacil`.`tipovia` (`id`, `desc`) VALUES (1, 'Calle');
INSERT INTO `casafacil`.`tipovia` (`id`, `desc`) VALUES (2, 'Avenida');
INSERT INTO `casafacil`.`tipovia` (`id`, `desc`) VALUES (3, 'Plaza');
INSERT INTO `casafacil`.`tipovia` (`id`, `desc`) VALUES (4, 'Camino');

COMMIT;


-- -----------------------------------------------------
-- Data for table `casafacil`.`ciudad`
-- -----------------------------------------------------
START TRANSACTION;
USE `casafacil`;
INSERT INTO `casafacil`.`ciudad` (`id`, `desc`) VALUES (1, 'Alicante');
INSERT INTO `casafacil`.`ciudad` (`id`, `desc`) VALUES (2, 'Valencia');
INSERT INTO `casafacil`.`ciudad` (`id`, `desc`) VALUES (3, 'Castellón');

COMMIT;


-- -----------------------------------------------------
-- Data for table `casafacil`.`barrio`
-- -----------------------------------------------------
START TRANSACTION;
USE `casafacil`;
INSERT INTO `casafacil`.`barrio` (`id`, `desc`, `codpostal`, `id_ciudad`) VALUES (1, 'Cabanyal', 46011, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `casafacil`.`extras`
-- -----------------------------------------------------
START TRANSACTION;
USE `casafacil`;
INSERT INTO `casafacil`.`extras` (`id`, `desc`) VALUES (1, 'Trastero');
INSERT INTO `casafacil`.`extras` (`id`, `desc`) VALUES (2, 'Parking Privado');
INSERT INTO `casafacil`.`extras` (`id`, `desc`) VALUES (3, 'Parking Compartido');
INSERT INTO `casafacil`.`extras` (`id`, `desc`) VALUES (4, 'Calefacción');

COMMIT;

